# Generated by Django 2.2.5 on 2019-12-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dPrice', models.PositiveIntegerField(max_length=4)),
            ],
        ),
    ]
