# Generated by Django 2.2.5 on 2019-12-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('eName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('eNum', models.PositiveIntegerField(max_length=4)),
                ('ePrice', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('FirmID', models.PositiveIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=20)),
                ('Tele', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('MemberID', models.PositiveIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('mName', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=13)),
                ('Email', models.EmailField(blank=True, max_length=100)),
                ('BDay', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sNum', models.PositiveIntegerField(max_length=4)),
                ('sPrice', models.PositiveIntegerField()),
                ('Expierd', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='dPrice',
            field=models.PositiveIntegerField(),
        ),
    ]
