# Generated by Django 2.2.5 on 2019-12-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='made',
            name='mID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='made',
            name='mTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
