# Generated by Django 2.2.5 on 2019-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20191219_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='eNum',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='MemberID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sNum',
            field=models.PositiveIntegerField(),
        ),
    ]
