# Generated by Django 2.2.5 on 2019-12-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20191227_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('invID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('invName', models.CharField(max_length=50)),
                ('invNum', models.PositiveIntegerField()),
                ('Expired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvideInventory',
            fields=[
                ('piTime', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('piNum', models.PositiveIntegerField()),
                ('pInvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Inventory')),
                ('piFirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Firm')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='made',
            name='mStock',
        ),
        migrations.AlterField(
            model_name='made',
            name='madeID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='oID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ProvideStock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='inventory',
            name='dish',
            field=models.ManyToManyField(through='production.Made', to='production.Dish'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='firm',
            field=models.ManyToManyField(through='production.ProvideInventory', to='production.Firm'),
        ),
        migrations.AddField(
            model_name='made',
            name='mInvent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.Inventory'),
            preserve_default=False,
        ),
    ]
