# Generated by Django 2.2.5 on 2019-12-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20191219_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oTime', models.DateTimeField(auto_now_add=True)),
                ('oNum', models.PositiveIntegerField()),
                ('MemberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Member')),
                ('dName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Dish')),
            ],
            options={
                'unique_together': {('oTime', 'MemberID', 'dName')},
            },
        ),
    ]
