# Generated by Django 2.2.5 on 2019-12-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20191227_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='MemberID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
