# Generated by Django 2.2.5 on 2019-12-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvideStock',
            fields=[
                ('psTime', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('psNum', models.PositiveIntegerField()),
                ('pStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Stock')),
                ('psFirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Firm')),
            ],
            options={
                'unique_together': {('psTime', 'pStock', 'psNum')},
            },
        ),
        migrations.CreateModel(
            name='ProvideEquip',
            fields=[
                ('peTime', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('peNum', models.PositiveIntegerField()),
                ('pEquip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Equipment')),
                ('peFirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Firm')),
            ],
            options={
                'unique_together': {('peTime', 'pEquip', 'peNum')},
            },
        ),
        migrations.CreateModel(
            name='Made',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mTime', models.DateTimeField(auto_now_add=True)),
                ('mNum', models.PositiveIntegerField()),
                ('mDish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Dish')),
                ('mStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Stock')),
            ],
            options={
                'unique_together': {('mTime', 'mDish', 'mStock')},
            },
        ),
    ]
