# Generated by Django 2.2.5 on 2019-12-21 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_made_provideequip_providestock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Expierd',
            new_name='Expired',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('sName', 'Expired')},
        ),
    ]
