# Generated by Django 2.2.5 on 2019-12-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20191221_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='MemberID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
