# Generated by Django 2.2.5 on 2019-12-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20191221_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='members',
            field=models.ManyToManyField(through='production.Order', to='production.Member'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='efirm',
            field=models.ManyToManyField(through='production.ProvideEquip', to='production.Firm'),
        ),
        migrations.AddField(
            model_name='stock',
            name='dishes',
            field=models.ManyToManyField(through='production.Made', to='production.Dish'),
        ),
        migrations.AddField(
            model_name='stock',
            name='sfirm',
            field=models.ManyToManyField(through='production.ProvideStock', to='production.Firm'),
        ),
        migrations.AlterField(
            model_name='member',
            name='MemberID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
