# Generated by Django 2.2.5 on 2019-12-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20191221_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='members',
            new_name='memberid',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='efirm',
            new_name='firm',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='dishes',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='sfirm',
            new_name='firm',
        ),
        migrations.AlterField(
            model_name='made',
            name='mTime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='oTime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provideequip',
            name='peTime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providestock',
            name='psTime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
