# Generated by Django 2.2.5 on 2019-12-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_auto_20191221_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='memberid',
            new_name='Mid',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='Expired',
            new_name='Expierd',
        ),
        migrations.AlterField(
            model_name='made',
            name='mTime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='oTime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provideequip',
            name='peTime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providestock',
            name='psTime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
