# Generated by Django 2.2.5 on 2019-12-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_auto_20191221_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Expierd',
            new_name='Expired',
        ),
    ]
