# Generated by Django 3.0 on 2019-12-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_auto_20191221_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Pets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Student',
            field=models.BooleanField(default=True),
        ),
    ]
