# Generated by Django 2.2.5 on 2019-12-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_auto_20191225_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='MemberID',
            new_name='MID',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dName',
            new_name='dishName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='oNum',
            new_name='orderNum',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ePrice',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sPrice',
        ),
        migrations.AlterField(
            model_name='order',
            name='oTime',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('oTime', 'MID', 'dishName')},
        ),
    ]
