# Generated by Django 3.0.1 on 2019-12-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_auto_20191226_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='made',
            name='mID',
            field=models.PositiveIntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order',
            name='oID',
            field=models.PositiveIntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='provideequip',
            name='peID',
            field=models.PositiveIntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='providestock',
            name='psID',
            field=models.PositiveIntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='sID',
            field=models.PositiveIntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='made',
            name='mTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='oTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='provideequip',
            name='peTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='providestock',
            name='psTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='made',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='provideequip',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='providestock',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
