# Generated by Django 3.0.1 on 2019-12-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_auto_20191227_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='made',
            name='mID',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='oID',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provideequip',
            name='peID',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providestock',
            name='psID',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sID',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
